### ISSUE TITLE
Primitive attributes entries accessors with different bufferView

### ISSUE THREAD

**Issue by martinlaxenaire** [toji/sponza-optimized#1]
Hi @toji,

This is not really an issue but more of a general question.

While working on a WebGPU glTF loader, I've decided to try using your optimized sponza model as a complex interleaved buffers test case.
I was able to render the whole model correctly, except for the green curtains that were not showing. I found it kinda weird so I decided to investigate a bit.

I discovered that every `primitive.attributes` accessors always shared the same `bufferView` (which makes sense, since the data are supposed to be interleaved), except for the green curtains, where the UV attribute seemed to come from elsewhere in the `ArrayBuffer`.

This can be seen by simply logging this to the console:
```javascript
console.log(
  Object.values(primitive.attributes).map((accessorIndex) => this.gltf.accessors[accessorIndex].bufferView)
)
```

![image](https://github.com/toji/sponza-optimized/assets/38728843/2b8dafaf-4490-484c-af56-31d706e21915)

Since the glTF specs does not specify anything about this, I guess this is strictly speaking a valid case, but isn't it a bit confusing?
I assume it's done that way to save some space and reuse UVs declared elsewhere (in this case, the blue curtains ones).

How can we deal with this situation? Are we supposed to reconstruct an interleaved array based on the different primitive attributes from scratch?

Thank you,

**Comment by toji** [comment]
This is an interesting edge case, I didn't realize that the file did this. It's not something that I did intentionally but instead is  due to the tool that I processed the file with: [glTF Transform](https://gltf-transform.dev/). To that end, I'm wondering if @donmccurdy has any insight as to why the attributes may have ended up being broken up this way. 

I'm pretty sure that for these files I did a export from Blender with default settings, then run it through the glTF Transform 
 CLI with the `dedupe` and `prune` options. (The Draco and KTX versions then layered on those options as needed)

That aside, this IS a valid way to store attributes for any glTF file, which offers no guarantees as to the structure of attributes. Yes, that's fairly annoying to code around in some cases, but if you want to build a robust glTF renderer then it's simply something that you need to support.

**Comment by donmccurdy** [comment]
Currently glTF Transform — when interleaved output is enabled — assigns accessors to buffer view groups based on the parent mesh primitive. If one primitive's accessors are a strict subset of another primitive's accessors, they may share the same buffer view. If the accessors overlap but neither is a strict subset, one primitive will reference its own buffer view and the other's as well.

Another important case where this can happen is Meshopt compression. Some compression settings are configured per buffer view, and different types of vertex attributes require different settings, so it would be normal to see more than one buffer view per primitive there as well.

Since there does seem to be only a single accessor being shared here ...

<details>
<summary>accessors and bufferviews for each primitive</summary>

```jsonld
{ accessors: [ 0, 1, 2, 3 ], bufferViews: [ 0 ] }
{ accessors: [ 4, 5, 6, 7 ], bufferViews: [ 1 ] }
{ accessors: [ 8, 9, 10, 11 ], bufferViews: [ 2 ] }
{ accessors: [ 12, 13, 14, 15 ], bufferViews: [ 3 ] }
{ accessors: [ 16, 17, 18, 19 ], bufferViews: [ 4 ] }
{ accessors: [ 20, 21, 22, 23 ], bufferViews: [ 5 ] }
{ accessors: [ 24, 25, 26, 27 ], bufferViews: [ 6 ] }
{ accessors: [ 28, 29, 30, 31 ], bufferViews: [ 7 ] }
{ accessors: [ 32, 33, 34, 35 ], bufferViews: [ 8 ] }
{ accessors: [ 36, 37, 38, 39 ], bufferViews: [ 9 ] }
{ accessors: [ 40, 41, 42, 43 ], bufferViews: [ 10 ] }
{ accessors: [ 44, 45, 46, 47 ], bufferViews: [ 11 ] }
{ accessors: [ 48, 49, 50, 51 ], bufferViews: [ 12 ] }
{ accessors: [ 52, 53, 54, 47 ], bufferViews: [ 13, 11 ] }
{ accessors: [ 55, 56, 57, 58 ], bufferViews: [ 14 ] }
{ accessors: [ 59, 60, 61, 62 ], bufferViews: [ 15 ] }
{ accessors: [ 63, 64, 65, 66 ], bufferViews: [ 16 ] }
{ accessors: [ 67, 68, 69, 70 ], bufferViews: [ 17 ] }
{ accessors: [ 71, 72, 73, 74 ], bufferViews: [ 18 ] }
{ accessors: [ 75, 76, 77, 78 ], bufferViews: [ 19 ] }
{ accessors: [ 79, 80, 81, 82 ], bufferViews: [ 20 ] }
{ accessors: [ 83, 84, 85, 86 ], bufferViews: [ 21 ] }
{ accessors: [ 87, 88, 89, 90 ], bufferViews: [ 22 ] }
{ accessors: [ 91, 92, 93, 94 ], bufferViews: [ 23 ] }
{ accessors: [ 95, 96, 97, 98 ], bufferViews: [ 24 ] }
{ accessors: [ 99, 100, 101, 102 ], bufferViews: [ 25 ] }
{ accessors: [ 103, 104, 105, 106 ], bufferViews: [ 26 ] }
{ accessors: [ 107, 108, 109, 110 ], bufferViews: [ 27 ] }
{ accessors: [ 111, 112, 113, 114 ], bufferViews: [ 28 ] }
{ accessors: [ 115, 116, 117, 118 ], bufferViews: [ 29 ] }
{ accessors: [ 119, 120, 121, 122 ], bufferViews: [ 30 ] }
{ accessors: [ 123, 124, 125, 126 ], bufferViews: [ 31 ] }
{ accessors: [ 127, 128, 129, 130 ], bufferViews: [ 32 ] }
```
</details>

... perhaps the `dedup()` step, combining duplicate accessors, is not necessary in this case?

**Comment by martinlaxenaire** [comment]
Thanks @toji and @donmccurdy for those explanations. It does make sense now.

I've decided to handle that edge case by rebuilding a clean interleaved array to use with my `GPUBuffer`. I'd probably still have to test with other models using similar glTF Transform settings, but it does work with that one now so I guess that'll do for now!

Cheers,
